server:
  port: 9001
spring:
  application:
    name: cloud-keymaker-service-api
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        healthCheckPath: ${management.context-path}/consul/health
        healthCheckInterval: 10s
        heartbeat:
          enabled: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/key_maker?serverTimezone=Asia/Shanghai&amp;useUnicode=true&amp;characterEncoding=utf8&amp;charset=utf8
    username: root
    password: qq19971102
    druid:
      initial-size: 5
      min-idle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        url-pattern: "/drxuid/*"
        allow:
        deny:
        reset-enable: false
        login-username: admin
        login-password: qq19971102
        enabled: true
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    redis:
      database: 0
      host: 127.0.0.1
      password: qq19971102
      pool:
        max-active: 20
        max-idle: 10
        max-wait: -1
        min-idle: 0
      port: 6379
      timeout: 0
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      #采样率介于0~1,1表示全部采集
#      probability: 1
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cloud.springcloud.entity.**

initCaches:
  apiListCache: 100s